sonar.projectKey=NovySoyuz_devops-tasks-board
sonar.organization=novysoyuz

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__tests__/**,**/coverage/**

sonar.tests=backend/src/__tests__,frontend/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info