# infra/docker/docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:15
    container_name: devops_tasks_db
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - devops_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: devops_tasks_keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - devops_net

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: devops_tasks_backend
    environment:
      PORT: 3000
      DATABASE_URL: postgres://devops:devops@db:5432/tasksdb
      NODE_ENV: development
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_ISSUER: http://localhost:8080
      KEYCLOAK_REALM: devops-tasks
      KEYCLOAK_CLIENT_ID: devops-tasks-frontend
    depends_on:
      - db
      - keycloak
    ports:
      - "3000:3000"
    networks:
      - devops_net

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: devops_tasks_frontend
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_KEYCLOAK_URL: http://localhost:8080
      VITE_KEYCLOAK_REALM: devops-tasks
      VITE_KEYCLOAK_CLIENT_ID: devops-tasks-frontend
    depends_on:
      - backend
      - keycloak
    ports:
      - "5173:5173"
    networks:
      - devops_net

volumes:
  db_data:
  keycloak_data:

networks:
  devops_net:
    driver: bridge