apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: devops-tasks
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-tasks
      tier: frontend
  template:
    metadata:
      labels:
        app: devops-tasks
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: tasks-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "/api"
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: devops-tasks-config
                  key: KEYCLOAK_REALM
            - name: VITE_KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: devops-tasks-config
                  key: KEYCLOAK_CLIENT_ID
            # VITE_KEYCLOAK_URL est injecté dynamiquement via kubectl set env (make k8s-https ou k8s-local)