apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-tasks-config
data:
  APP_ENV: "kubernetes"
  BACKEND_PORT: "3000"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_DB: "tasksdb"
  AUTH0_DOMAIN: "dev-iazccw3gseusnctx.eu.auth0.com"
  AUTH0_CLIENT_ID: "F1m7hqlwUsAdxVXTYvfhE7fsn4IlyvBz"
  AUTH0_AUDIENCE: "https://devops-tasks-api"
  FRONTEND_URL: "https://192.168.49.2"