apiVersion: v1
kind: Secret
metadata:
  name: devops-tasks-secret
type: Opaque
# ⚠️ Ne jamais committer de vraies valeurs ici.
# Générer ce fichier localement : kubectl create secret generic devops-tasks-secret --from-literal=...
stringData:
  POSTGRES_USER: "devops"
  POSTGRES_PASSWORD: "CHANGE_ME_BEFORE_DEPLOY"
  DATABASE_URL: "postgres://devops:CHANGE_ME_BEFORE_DEPLOY@postgres-service:5432/tasksdb"
  KEYCLOAK_ADMIN_USER: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "CHANGE_ME_BEFORE_DEPLOY"